site: Crypto-dissident
title: Crypto-dissident
greetings: "Hi 👋"
description: >
  "Bienvenue dans l'espace d'un 'Crypto-dissident'".
  Mon blog couvrira les news, articles, guides & projets sur le 'Bitcoin', le protocole Nostr, Tor (P2P), Blockchain; bref, la 'Décentralisation' & la sécurité des données...
  En outre, je suis des sujets liés à la cryptographie, la science des données, la programmation... Bref, l'Internet en général!
  Amusez-vous à lire, & faites quelques commentaires si vous le souhaitez...

  “In a future that includes competition from open source, we can expect that the eventual destiny of any software technology will be to either die or become part of the open infrastructure itself.”
  ― Eric S. Raymond, The Cathedral & the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary.

lang: en
image: "https://turnoff.us/image/en/protocols.png"
timezone: Africa/Lome
repo: "https://github.com/Ferrerkomi/segnibokomi.github.io" # site repo [optional]
data-theme: light # default theme "dark" | "light"
disqus-identifier: webthme
default-thumb: "https://res.cloudinary.com/notee/image/upload/v1640412257/notes/default-thumb.webp"

author:
  name: Komi Segnibo
  url: "https://ferrerkomi.github.io/segnibokomi.github.io/"
  bio: "Juste un Cyber-chercheur au fond du 'Rabbit-Hole'.
  Nous ne sommes pas ici parce que nous sommes libres, 
  Nous sommes ici parce que nous ne sommes pas libres...
  
  'Crypto-anarchy is unforgiving of crypto-apathy.' ― Jacob Riggs"
  
  avatar: "https://robohash.org/crypto-dissident"
  username: Komi Hartman # general username
  github: Ferrerkomi # github username
  twitter: Komi_Hartman # twitter username
  email: segnibo2@icloud.com # email address

twitter:
  username: Komi_Hartman
  card: summary_large_image

# Font Settings
googlewebfonts: "family=Archivo:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900"

# URL settings
url: "https://ferrerkomi.github.io/segnibokomi.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/" # subfolder for jekyll site. only if jekyll site not in root of host. leave blank if not wished. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" #
# baseurl: "" #

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links

paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: "/:name"
  posts:
    output: true
    permalink: "/:slug"
  authors:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      image: "https://turnoff.us/image/en/ode-to-my-family.png"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

relative_links:
  enabled: true
  collections: false
