# Build Jekyll and Deploy to Github Pages
name: Jekyll site CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
- name: Save state
run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
run: echo "{name}={value}" >> $GITHUB_OUTPUT
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build
    - name: 👷 Build the site in the jekyll container 
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll &&\
        jekyll build --future -d _site"
    
    # Deploy to gh-pages branch
    - name: 🚀 Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: main # The branch the action should deploy to.
        folder: _site # The folder the action should deploy.
